[project]
name = "docs"
version = "0.1.0"
description = "The official Judge0 documentation."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "sphinx>=8.2.3",
    "sphinxawesome-theme>=5.3.2",
]
